<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Mobile Phone' => 'Número de teléfono móvil',
  'cannot be blank' => '@@@@no puede estar en blanco@@@@',
  ' are required.' => ' son obligatorios.',
  'Account Type' => 'Tipo de Cuenta',
  'Country' => 'País',
  'E-mail' => 'E-mail',
  'Fields with ' => 'Los campos con ',
  'First Name' => 'Nombre',
  'Password' => 'Contraseña',
  'Please fill out the following form with your login credentials:' => 'Por favor, rellene el siguiente formulario con sus credenciales de inicio de sesión:',
  'Registration' => 'Registro',
  'Remember me next time' => 'Recordarme la próxima vez',
  'Repeat Password' => 'Repita la contraseña',
  'Surname' => 'Apellido',
  'Username' => 'Nombre de usuario',
  'Account Type'=>'Tipo de Cuenta',
);
