<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'ICT' => '',
  'Legal' => '',
  'About Us' => 'Acerca de Nosotros',
  'Accounting/Bookkeeping' => 'Contabilidad ',
  'Aquiring skills, tools, and strategies' => 'La adquisición de habilidades, herramientas y estrategias',
  'Business Strategy' => 'Estrategia de Negocios',
  'Contact Us' => 'Contacte con nosotros',
  'Developing a healthy mindset' => 'El desarrollo de una mentalidad sana',
  'Enjoy high quality mentoring' => 'Disfrute de tutoría de alta calidad',
  'Executive Coaching' => 'coaching Ejecutivo',
  'Funding' => 'financiamiento',
  'Gain access to funding' => 'Acceso a la financiación',
  'Get information on opportunities to fund your ideas' => 'Obtener información sobre oportunidades de financiar sus ideas',
  'Get quality services at discounted rates' => 'Obtener servicios de calidad a precios reducidos',
  'Get your business off the ground' => 'Conseguir que su negocio fuera de la tierra',
  'Getting the business started' => 'Obtención de la empresa comenzó',
  'Growing the business' => 'El crecimiento del negocio',
  'Guarantee the success of your business' => 'Garantizar el éxito de su negocio',
  'HR Team development' => 'equipo de desarrollo',
  'HR/Payroll' => 'de Recursos Humanos',
  'Have your profile looked by potential parners and investors' => 'Que su perfil buscado por Parners y los inversores potenciales',
  'Home' => 'casa',
  'How it works' => 'Cómo funciona',
  'Innovation' => 'innovación',
  'Instant access to world class Virtual Business Incubation...' => 'Acceso instantáneo al mundo de Incubación de Empresas de clase virtual',
  'Introduction to the vcubator' => 'Introducción a la vcubator',
  'Log in' => 'acceder',
  'Log out' => 'salir',
  'Marketing' => 'mercadeo',
  'Marketing Support' => 'apoyo a la comercialización',
  'Mentoring' => 'mentoring',
  'Register Now' => 'Regístrese ahora',
  'Running the business' => 'Funcionamiento de la empresa',
  'Services' => 'servicios',
  'Strategic Leadership' => 'Liderazgo Estratégico',
  'Tap into our amazing network of investors and financiers' => 'Aproveche nuestra increíble red de inversionistas y financieros',
  'Tax' => 'impuesto',
  'Terms and Conditions' => 'Términos y Condiciones',
  'Training' => 'formación',
  'What you get on the Vcubator' => 'Lo que se obtiene en el Vcubator',
  'Sorry this email has already been registered as a Service Provider'=>'Lo siento, este correo electrónico ya se ha registrado como Proveedor de Servicios',
);
