<?php
return array(
			'class'=>'PaymentTransaction',
			'paymentOptions'=>array(				
				'paypal'=>'PayPal',
				'payfast'=>'Credit Card and Electronic Funds Transfer',
				'purse'=>'My Purse',
			),
			'brands'=>array(
				'paypal'=>'paypal.png',
				'payfast'=>'credit_cards.png',
				'purse'=>'purse.png',
			),			
			'transactionCharge'=>array(
				'payfast'=>array(							
							'add'=>8,
							'currency'=>'ZAR',
							'multiply'=>0.049,
						),
				'paypal'=>array(							
							'add'=>0.30,
							'currency'=>'USD',
							'multiply'=>0.034,
						),
				'purse'=>array(
							'multiply'=>0,
						),
			),
			'confirmPage'=>'application.components.payment.views.confirm',
			'gatewayConfig'=>array(
				'typeA' => array(
					'paypal'=> array(
						array(
							'tag'=>'form', 
							'htmlOptions'=>array(
								'action'=>'https://www.sandbox.paypal.com/cgi-bin/webscr',
								 'method'=>'post',								
							)
						),						
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								'name'=>'cmd', 
								'value'=>"_s-xclick"
							)
						),
						array(
							'tag'=>'input',
							'htmlOptions'=>array(
								'type'=>'hidden',
								'name'=>'hosted_button_id', 
								'value'=>"FMLTMD64EXT2A",									
							)
						),
						array(
							 'tag'=>'input',
							 'htmlOptions'=>array(
							 	'type'=>'image',
								'name'=>'submit', 
								'src'=>"https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif", 
								'border'=>"0", 
								"alt"=>"PayPal - The safer, easier way to pay online!",								
								'class'=>'neutralize',
							)
						),
						array(
							'tag'=>'img',
							'htmlOptions'=>array( 
								'border'=>'0', 
								'src'=>'https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif', 
								'width'=>"1", 
								'height'=>'1'
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'first_name',
								 'generate-data'=>'firstname',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'last_name',
								 'generate-data'=>'lastname',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'email',
								 'generate-data'=>'email',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'address1',
								 'generate-data'=>'address_firstline',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'address2',
								 'generate-data'=>'address_secondline',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'city',
								 'generate-data'=>'address_city',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'country',
								 'generate-data'=>'address_country_code',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'zip',
								 'generate-data'=>'postal_code',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'cancel_return',
								 'value'=>'http://thevcubator.com/payments/paypal_cancel?',
								 'append'=>array(
									'payment_id'=>'enc_payment_id',
								),															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'return',
								 'value'=>'http://thevcubator.com/paypal_success.php?sandbox=1',
								 'append'=>array(
									'payment_id'=>'enc_payment_id',
								),															 
							)
						),
					),
					'payfast'=> array(
						array(
							'tag'=>'form', 
							'htmlOptions'=>array(
								'action'=>'https://www.payfast.co.za/eng/process',
								 'method'=>'post',
								 'name'=>'frmPay',
								 'id'=>'frmPay',
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'merchant_id',
								 'value'=>'10090544',								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'merchant_key',
								 'value'=>'kldm5ulwuqjke',								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'return_url',
								 'value'=>'http://vcubator.com/payment/finished',								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'cancel_url',
								 'value'=>'http://vcubator.com/payment/cancelled',								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'notify_url',
								 'value'=>'http://vcubator.com/payment/notify'								 
							)
						),
				//transaction specific data
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'name_first',
								 'generate-data'=>'firstname',								 								 
							)
						),	
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'name_last',
								 'generate-data'=>'lastname',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'email_address',
								 'generate-data'=>'email',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'m_payment_id',
								 'generate-data'=>'payment_id',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'amount',
								 'generate-data'=>'amount',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'item_name',
								 'generate-data'=>'item_name',															 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'item_description',
								 'generate-data'=>'item_description',															 
							)
						),						
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'email_confirmation',
								 'value'=>'1',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'confirmation_address',
								 'generate-data'=>'confirmation_address',								 								 
							)
						),
						array(
							'tag'=>'input', 
							'htmlOptions'=>array(
								'type'=>'hidden',
								 'name'=>'signature',
								 'generate-data'=>'security_signature',																 
							)
						),														
					),
					'purse'=>array(),
				)
			),	
);
?>