<?php
Yii::import('zii.widgets.CMenu');

class MappedMenu extends CMenu {
	
	public $controllerMapping = array();
	
	/**
	 * Checks whether a menu item is active.
	 * This is done by checking if the currently requested URL is generated by the 'url' option
	 * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
	 * @param array $item the menu item to be checked
	 * @param string $route the route of the current request
	 * @return boolean whether the menu item is active
	 */
	protected function isItemActive($item,$route)
	{
		if(is_array($this->controllerMapping)&& array_key_exists($item['label'], $this->controllerMapping))
		{						
			$mappedControllers = $this->controllerMapping[$item['label']];
			if(in_array($this->controller->id, $mappedControllers))
				return true;
		}
		if((isset($item['url']) && is_array($item['url']) && !strcasecmp(trim($item['url'][0],'/'),$route)))
		{ 
			if(count($item['url'])>1)
			{
				foreach(array_splice($item['url'],1) as $name=>$value)
				{
					if(!isset($_GET[$name]) || $_GET[$name]!=$value)
						return false;
				}
			}
			return true;
		}
		return false;
	}
}

?>