<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'About Us' => '',
  'Accounting/Bookkeeping' => '',
  'Aquiring skills, tools, and strategies' => '',
  'Business Strategy' => '',
  'Contact Us' => '',
  'Developing a healthy mindset' => '',
  'Enjoy high quality mentoring' => '',
  'Executive Coaching' => '',
  'Funding' => '',
  'Gain access to funding' => '',
  'Get information on opportunities to fund your ideas' => '',
  'Get quality services at discounted rates' => '',
  'Get your business off the ground' => '',
  'Getting the business started' => '',
  'Growing the business' => '',
  'Guarantee the success of your business' => '',
  'HR Team development' => '',
  'HR/Payroll' => '',
  'Have your profile looked by potential parners and investors' => '',
  'Home' => '',
  'How it works' => '',
  'ICT' => '',
  'Innovation' => '',
  'Instant access to world class Virtual Business Incubation...' => '',
  'Introduction to the vcubator' => '',
  'Legal' => '',
  'Log in' => '',
  'Log out' => '',
  'Marketing' => '',
  'Marketing Support' => '',
  'Mentoring' => '',
  'Register Now' => '',
  'Running the business' => '',
  'Services' => '',
  'Strategic Leadership' => '',
  'Tap into our amazing network of investors and financiers' => '',
  'Tax' => '',
  'Terms and Conditions' => '',
  'Training' => '',
  'What you get on the Vcubator' => '',
);
